### ISSUE TITLE
chore: update changelog for next release (1.7.0?)

### ISSUE THREAD

**Issue by stennie** [basti1302/repoman#69]
Summarise the changes from 1.6.0.

Currently there is change history up to 1.0.0 in CHANGELOG.md and a brief history of newer changes in the README.md.

I suggest consolidating the history in the changelog so there's only one place to review.

**Comment by basti1302** [comment]
I add some release automation, which should hopefully take care of updating the changelog automatically.

**Comment by basti1302** [comment]
@stennie Just a quick heads up: I had to rewrite most commit message since release 1.6.0 to the conventional commit format so that the release automation works correctly and can generate a changelog from the commit messages. This involved force-pushing to main. You might want to update your local clone of the repo.

**Comment by stennie** [comment]
Thanks @basti1302! Lots of nice clean up for this release 👍
